/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class Seats extends javax.swing.JFrame {
    
    String movName, timing;
    ArrayList <String> seats = new ArrayList<String>();
    /** Creates new form Main */
    public Seats(String movName, String timing) {
        this.movName = movName;
        this.timing = timing;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proceed = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        B9 = new javax.swing.JLabel();
        B10 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C9 = new javax.swing.JLabel();
        C10 = new javax.swing.JLabel();
        SCREEN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Ticket Booking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 137, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select seats:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo_small.png"))); // NOI18N

        proceed.setBackground(new java.awt.Color(22, 115, 233));
        proceed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        proceed.setForeground(new java.awt.Color(255, 255, 255));
        proceed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proceed.setText("Proceed");
        proceed.setOpaque(true);
        proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proceedMousePressed(evt);
            }
        });

        back.setBackground(new java.awt.Color(70, 106, 151));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(60, 75, 88));

        A1.setBackground(new java.awt.Color(128, 128, 128));
        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setText("A1");
        A1.setOpaque(true);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A1MousePressed(evt);
            }
        });

        A2.setBackground(new java.awt.Color(128, 128, 128));
        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setText("A2");
        A2.setOpaque(true);
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A2MouseReleased(evt);
            }
        });

        A3.setBackground(new java.awt.Color(128, 128, 128));
        A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A3.setText("A3");
        A3.setOpaque(true);
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A3MousePressed(evt);
            }
        });

        A4.setBackground(new java.awt.Color(128, 128, 128));
        A4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A4.setText("A4");
        A4.setOpaque(true);
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A4MousePressed(evt);
            }
        });

        A5.setBackground(new java.awt.Color(128, 128, 128));
        A5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A5.setText("A5");
        A5.setOpaque(true);
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A5MousePressed(evt);
            }
        });

        A6.setBackground(new java.awt.Color(128, 128, 128));
        A6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A6.setText("A6");
        A6.setOpaque(true);
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A6MousePressed(evt);
            }
        });

        A7.setBackground(new java.awt.Color(128, 128, 128));
        A7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A7.setText("A7");
        A7.setOpaque(true);
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A7MousePressed(evt);
            }
        });

        A8.setBackground(new java.awt.Color(128, 128, 128));
        A8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A8.setText("A8");
        A8.setOpaque(true);
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A8MousePressed(evt);
            }
        });

        A9.setBackground(new java.awt.Color(128, 128, 128));
        A9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A9.setText("A9");
        A9.setOpaque(true);
        A9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A9MousePressed(evt);
            }
        });

        A10.setBackground(new java.awt.Color(128, 128, 128));
        A10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A10.setText("A10");
        A10.setOpaque(true);
        A10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A10MousePressed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(128, 128, 128));
        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setText("B1");
        B1.setOpaque(true);
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B1MousePressed(evt);
            }
        });

        C1.setBackground(new java.awt.Color(128, 128, 128));
        C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C1.setText("C1");
        C1.setOpaque(true);
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C1MousePressed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(128, 128, 128));
        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setText("B2");
        B2.setOpaque(true);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B2MousePressed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(128, 128, 128));
        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setText("B3");
        B3.setOpaque(true);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B3MousePressed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(128, 128, 128));
        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setText("B4");
        B4.setOpaque(true);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B4MousePressed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(128, 128, 128));
        B5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5.setText("B5");
        B5.setOpaque(true);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B5MousePressed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(128, 128, 128));
        B6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B6.setText("B6");
        B6.setOpaque(true);
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B6MousePressed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(128, 128, 128));
        B7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B7.setText("B8");
        B7.setOpaque(true);
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B7MousePressed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(128, 128, 128));
        B8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B8.setText("B7");
        B8.setOpaque(true);
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B8MousePressed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(128, 128, 128));
        B9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B9.setText("B9");
        B9.setOpaque(true);
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B9MousePressed(evt);
            }
        });

        B10.setBackground(new java.awt.Color(128, 128, 128));
        B10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B10.setText("B10");
        B10.setOpaque(true);
        B10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B10MousePressed(evt);
            }
        });

        C2.setBackground(new java.awt.Color(128, 128, 128));
        C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C2.setText("C2");
        C2.setOpaque(true);
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C2MousePressed(evt);
            }
        });

        C3.setBackground(new java.awt.Color(128, 128, 128));
        C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C3.setText("C3");
        C3.setOpaque(true);
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C3MousePressed(evt);
            }
        });

        C4.setBackground(new java.awt.Color(128, 128, 128));
        C4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C4.setText("C4");
        C4.setOpaque(true);
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C4MousePressed(evt);
            }
        });

        C5.setBackground(new java.awt.Color(128, 128, 128));
        C5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C5.setText("C5");
        C5.setOpaque(true);
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C5MousePressed(evt);
            }
        });

        C6.setBackground(new java.awt.Color(128, 128, 128));
        C6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C6.setText("C6");
        C6.setOpaque(true);
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C6MousePressed(evt);
            }
        });

        C7.setBackground(new java.awt.Color(128, 128, 128));
        C7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C7.setText("C7");
        C7.setOpaque(true);
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C7MousePressed(evt);
            }
        });

        C8.setBackground(new java.awt.Color(128, 128, 128));
        C8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C8.setText("C8");
        C8.setOpaque(true);
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C8MousePressed(evt);
            }
        });

        C9.setBackground(new java.awt.Color(128, 128, 128));
        C9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C9.setText("C9");
        C9.setOpaque(true);
        C9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C9MousePressed(evt);
            }
        });

        C10.setBackground(new java.awt.Color(128, 128, 128));
        C10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C10.setText("C10");
        C10.setOpaque(true);
        C10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                C10MousePressed(evt);
            }
        });

        SCREEN.setBackground(new java.awt.Color(48, 48, 48));
        SCREEN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SCREEN.setForeground(new java.awt.Color(232, 232, 232));
        SCREEN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SCREEN.setText("SCREEN THIS WAY");
        SCREEN.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(159, 159, 159))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(SCREEN, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(SCREEN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed
    
    boolean c1 = true;
    boolean c2 = true;
    boolean c3 = true;
    boolean c4 = true;
    boolean c5 = true;
    boolean c6 = true;
    boolean c7 = true;
    boolean c8 = true;
    boolean c9 = true;
    boolean c10 = true;
    boolean c11 = true;
    boolean c12 = true;
    boolean c13 = true;
    boolean c14 = true;
    boolean c15 = true;
    boolean c16 = true;
    boolean c17 = true;
    boolean c18 = true;
    boolean c19 = true;
    boolean c20 = true;
    boolean c21 = true;
    boolean c22 = true;
    boolean c23 = true;
    boolean c24 = true;
    boolean c25 = true;
    boolean c26 = true;
    boolean c27 = true;
    boolean c28 = true;
    boolean c29 = true;
    boolean c30 = true;
    
    private void A1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MousePressed
        // TODO add your handling code here:
        if(c1){
            A1.setBackground(Color.white);
            c1 = false;
            seats.add(A1.getText());
            return;
        }
        else{
            A1.setBackground(Color.gray);
            c1 = true;
            seats.remove(A1.getText());
            return;
        }
    }//GEN-LAST:event_A1MousePressed

    private void A2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_A2MouseReleased

    private void A2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MousePressed
        if(c2){
            A2.setBackground(Color.white);
            c2 = false;
            seats.add(A2.getText());
            return;
        }
        else{
            A2.setBackground(Color.gray);
            c2 = true;
            seats.remove(A2.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A2MousePressed

    private void A3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MousePressed
        if(c3){
            A3.setBackground(Color.white);
            c3 = false;
            seats.add(A3.getText());
            return;
        }
        else{
            A3.setBackground(Color.gray);
            c3 = true;
            seats.remove(A3.getText());

            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A3MousePressed

    private void A4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MousePressed
        if(c4){
            A4.setBackground(Color.white);
            c4 = false;
            seats.add(A4.getText());
            return;
        }
        else{
            A4.setBackground(Color.gray);
            c4 = true;
            seats.remove(A4.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A4MousePressed

    private void A5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A5MousePressed
        if(c5){
            A5.setBackground(Color.white);
            c5 = false;
            seats.add(A5.getText());
            return;
        }
        else{
            A5.setBackground(Color.gray);
            c5 = true;
            seats.remove(A5.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A5MousePressed

    private void A6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A6MousePressed
        if(c6){
            A6.setBackground(Color.white);
            c6 = false;
            seats.add(A6.getText());
            return;
        }
        else{
            A6.setBackground(Color.gray);
            c6 = true;
            seats.remove(A6.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A6MousePressed

    private void A7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A7MousePressed
       if(c7){
            A7.setBackground(Color.white);
            c7 = false;
            seats.add(A7.getText());
            return;
        }
        else{
            A7.setBackground(Color.gray);
            c7 = true;
            seats.remove(A7.getText());
            return;
        } // TODO add your handling code here:
    }//GEN-LAST:event_A7MousePressed

    private void A8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A8MousePressed
        if(c8){
            A8.setBackground(Color.white);
            c8 = false;
            seats.add(A8.getText());
            return;
        }
        else{
            A8.setBackground(Color.gray);
            c8 = true;
            seats.remove(A8.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A8MousePressed

    private void A9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A9MousePressed
        if(c9){
            A9.setBackground(Color.white);
            c9 = false;
            seats.add(A9.getText());
            return;
        }
        else{
            A9.setBackground(Color.gray);
            c9 = true;
            seats.remove(A9.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A9MousePressed

    private void A10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A10MousePressed
        if(c10){
            A10.setBackground(Color.white);
            c10 = false;
            seats.add(A10.getText());
            return;
        }
        else{
            A10.setBackground(Color.gray);
            c10 = true;
            seats.remove(A10.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_A10MousePressed

    private void B1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MousePressed
        if(c11){
            B1.setBackground(Color.white);
            c11 = false;
            seats.add(B1.getText());
            return;
        }
        else{
            B1.setBackground(Color.gray);
            c11 = true;
            seats.remove(B1.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B1MousePressed

    private void B2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MousePressed
        if(c12){
            B2.setBackground(Color.white);
            c12 = false;
            seats.add(B2.getText());
            return;
        }
        else{
            B2.setBackground(Color.gray);
            c12 = true;
            seats.remove(B2.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B2MousePressed

    private void B3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MousePressed
        if(c13){
            B3.setBackground(Color.white);
            c13 = false;
            seats.add(B3.getText());
            return;
        }
        else{
            B3.setBackground(Color.gray);
            c13 = true;
            seats.remove(B3.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B3MousePressed

    private void B4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MousePressed
        if(c14){
            B4.setBackground(Color.white);
            c14 = false;
            seats.add(B4.getText());
            return;
        }
        else{
            B4.setBackground(Color.gray);
            c14 = true;
            seats.remove(B4.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B4MousePressed

    private void B5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MousePressed
        if(c15){
            B5.setBackground(Color.white);
            c15 = false;
            seats.add(B5.getText());
            return;
        }
        else{
            B5.setBackground(Color.gray);
            c15 = true;
            seats.remove(B5.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B5MousePressed

    private void B6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MousePressed
        if(c16){
            B6.setBackground(Color.white);
            c16 = false;
            seats.add(B6.getText());
            return;
        }
        else{
            B6.setBackground(Color.gray);
            c16 = true;
            seats.remove(B6.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B6MousePressed

    private void B8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MousePressed
        if(c18){
            B8.setBackground(Color.white);
            c18 = false;
            seats.add(B8.getText());
            return;
        }
        else{
            B8.setBackground(Color.gray);
            c18 = true;
            seats.remove(B8.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B8MousePressed

    private void B7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MousePressed
        if(c17){
            B7.setBackground(Color.white);
            c17 = false;
            seats.add(B7.getText());
            return;
        }
        else{
            B7.setBackground(Color.gray);
            c17 = true;
            seats.remove(B7.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B7MousePressed

    private void B9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MousePressed
        if(c19){
            B9.setBackground(Color.white);
            c19 = false;
            seats.add(B9.getText());
            return;
        }
        else{
            B9.setBackground(Color.gray);
            c19 = true;
            seats.remove(B9.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B9MousePressed

    private void B10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B10MousePressed
        if(c20){
            B10.setBackground(Color.white);
            c20 = false;
            seats.add(B10.getText());
            return;
        }
        else{
            B10.setBackground(Color.gray);
            c20 = true;
            seats.remove(B10.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_B10MousePressed

    private void C1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MousePressed
        if(c21){
            C1.setBackground(Color.white);
            c21 = false;
            seats.add(C1.getText());
            return;
        }
        else{
            C1.setBackground(Color.gray);
            c21 = true;
            seats.remove(C1.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C1MousePressed

    private void C2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MousePressed
        if(c22){
            C2.setBackground(Color.white);
            c22 = false;
            seats.add(C2.getText());
            return;
        }
        else{
            C2.setBackground(Color.gray);
            c22 = true;
            seats.remove(C2.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C2MousePressed

    private void C3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MousePressed
        if(c23){
            C3.setBackground(Color.white);
            c23 = false;
            seats.add(C3.getText());
            return;
        }
        else{
            C3.setBackground(Color.gray);
            c23 = true;
            seats.remove(C3.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C3MousePressed

    private void C4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MousePressed
        if(c24){
            C4.setBackground(Color.white);
            c24 = false;
            seats.add(C4.getText());
            return;
        }
        else{
            C4.setBackground(Color.gray);
            c24 = true;
            seats.remove(C4.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C4MousePressed

    private void C5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MousePressed
        if(c25){
            C5.setBackground(Color.white);
            c25 = false;
            seats.add(C5.getText());
            return;
        }
        else{
            C5.setBackground(Color.gray);
            c25 = true;
            seats.remove(C5.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C5MousePressed

    private void C6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C6MousePressed
        if(c26){
            C6.setBackground(Color.white);
            c26 = false;
            seats.add(C6.getText());
            return;
        }
        else{
            C6.setBackground(Color.gray);
            c26 = true;
            seats.remove(C6.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C6MousePressed

    private void C7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C7MousePressed
        if(c27){
            C7.setBackground(Color.white);
            c27 = false;
            seats.add(C7.getText());
            return;
        }
        else{
            C7.setBackground(Color.gray);
            c27 = true;
            seats.remove(C7.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C7MousePressed

    private void C8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MousePressed
        if(c28){
            C8.setBackground(Color.white);
            c28 = false;
            seats.add(C8.getText());
            return;
        }
        else{
            C8.setBackground(Color.gray);
            c28 = true;
            seats.remove(C8.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C8MousePressed

    private void C9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C9MousePressed
        if(c29){
            C9.setBackground(Color.white);
            c29 = false;
            seats.add(C9.getText());
            return;
        }
        else{
            C9.setBackground(Color.gray);
            c29 = true;
            seats.remove(C9.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C9MousePressed

    private void C10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C10MousePressed
        if(c30){
            C10.setBackground(Color.white);
            c30 = false;
            seats.add(C10.getText());
            return;
        }
        else{
            C10.setBackground(Color.gray);
            c30 = true;
            seats.remove(C10.getText());
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_C10MousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new timingPage(movName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMousePressed

    private void proceedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedMousePressed
        if(seats.size()<=0){
            JOptionPane.showMessageDialog(Seats.this, "Please select your seat!");
            return;
        }
        else{
            new Details(movName, timing, seats).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_proceedMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Seats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A10;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B10;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel B9;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C10;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JLabel SCREEN;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel proceed;
    // End of variables declaration//GEN-END:variables

}
