/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app;

import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class timingPage extends javax.swing.JFrame {
    
    String movName;
    String timing;
    
    /** Creates new form Main */
    public timingPage(String movName) {
        this.movName = movName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timing01 = new javax.swing.JLabel();
        timing02 = new javax.swing.JLabel();
        timing03 = new javax.swing.JLabel();
        timing04 = new javax.swing.JLabel();
        timing05 = new javax.swing.JLabel();
        timing06 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Ticket Booking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 137, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Show timing:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo_small.png"))); // NOI18N

        timing01.setBackground(new java.awt.Color(245, 245, 245));
        timing01.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing01.setForeground(new java.awt.Color(61, 61, 61));
        timing01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing01.setText("7:30am");
        timing01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing01.setOpaque(true);
        timing01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timing01MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing01MousePressed(evt);
            }
        });

        timing02.setBackground(new java.awt.Color(245, 245, 245));
        timing02.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing02.setForeground(new java.awt.Color(61, 61, 61));
        timing02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing02.setText("10:00am");
        timing02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing02.setOpaque(true);
        timing02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing02MousePressed(evt);
            }
        });

        timing03.setBackground(new java.awt.Color(245, 245, 245));
        timing03.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing03.setForeground(new java.awt.Color(61, 61, 61));
        timing03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing03.setText("12:00pm");
        timing03.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing03.setOpaque(true);
        timing03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing03MousePressed(evt);
            }
        });

        timing04.setBackground(new java.awt.Color(245, 245, 245));
        timing04.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing04.setForeground(new java.awt.Color(61, 61, 61));
        timing04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing04.setText("4:30pm");
        timing04.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing04.setOpaque(true);
        timing04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing04MousePressed(evt);
            }
        });

        timing05.setBackground(new java.awt.Color(245, 245, 245));
        timing05.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing05.setForeground(new java.awt.Color(61, 61, 61));
        timing05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing05.setText("8:00pm");
        timing05.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing05.setOpaque(true);
        timing05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing05MousePressed(evt);
            }
        });

        timing06.setBackground(new java.awt.Color(245, 245, 245));
        timing06.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timing06.setForeground(new java.awt.Color(61, 61, 61));
        timing06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timing06.setText("10:30pm");
        timing06.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        timing06.setOpaque(true);
        timing06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timing06MousePressed(evt);
            }
        });

        back.setBackground(new java.awt.Color(70, 106, 151));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33))
                            .addComponent(timing04, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timing01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timing05, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timing02, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timing06, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timing03, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timing01, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timing02, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timing03, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(timing04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timing06, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timing05, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void timing01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing01MouseClicked
        // no using
        
    }//GEN-LAST:event_timing01MouseClicked

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        new BookingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMousePressed

    private void timing01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing01MousePressed
        timing = "7:30am";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing01MousePressed

    private void timing02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing02MousePressed
        timing = "10:00am";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing02MousePressed

    private void timing03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing03MousePressed
        timing = "12:00pm";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing03MousePressed

    private void timing04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing04MousePressed
        timing = "4:30pm";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing04MousePressed

    private void timing05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing05MousePressed
        timing = "8:00pm";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing05MousePressed

    private void timing06MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timing06MousePressed
        timing = "10:30pm";
        new Seats(movName, timing).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timing06MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new timingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel timing01;
    private javax.swing.JLabel timing02;
    private javax.swing.JLabel timing03;
    private javax.swing.JLabel timing04;
    private javax.swing.JLabel timing05;
    private javax.swing.JLabel timing06;
    // End of variables declaration//GEN-END:variables

}
